### ISSUE TITLE
Code completion not working.

### ISSUE THREAD

**Issue by Disar** [stef-levesque/vscode-shader#17]
I see on the details page some shots for Completion Proposals  and  Help With Function and Method Signatures. But non of that works in glsl files?
Im on version 1.1.3

**Comment by stef-levesque** [comment]
Exact, it is currently only supported for HLSL. Although, support for GLSL is in progress.

**Comment by einarpersson** [comment]
This is not at all obvious. I've just wasted 45 mins troubleshooting why GLSL was not working. That is kinda annoying.
![image](https://user-images.githubusercontent.com/6043691/71379991-df1d8a80-25cd-11ea-8775-32f11544cf5d.png)

Please change description / update documentation so that this is clear for anyone considering this extension atm.

**Comment by Disar** [comment]
@einarpersson  alternatively you can use the glsl validator binaries with one of the glsl linters extensions. It will squiggle your errors.
